### ISSUE TITLE
Klik na dugme "Evidencija lotova" ne radi ništa

### ISSUE THREAD

**Issue by NerminBoja** [SoftverInzenjeringETFSA/SI2015Tim1#26]
commit ID: 
8ab577353ad033fb8d044ac3ab12a6f4033bf69a

Opis problema: Kada se menadžer loguje na sistem, i želi da evidentira lotove klikom na "Evidencija lotova", ništa se ne dešava

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "SIDEVS"
2. Logovati se kao menadžer.
3. Kliknuti na dugme "Evidencija lotova"

**Comment by MaidaB** [comment]
Ja sam klonirala ponovo repozitorij i zaista rade ovi buttoni molim te provjeri jesi li povukao ispravnu verziju

**Comment by MaidaB** [comment]
neki problem s lokalnom bazom..
