### ISSUE TITLE
Klik na dugme "Dodaj/ažuriraj lotove" ne radi ništa

### ISSUE THREAD

**Issue by NerminBoja** [SoftverInzenjeringETFSA/SI2015Tim1#27]
commit ID: 
8ab5773

Opis problema: Kada se menadžer loguje na sistem, i želi da doda/ažurira lotove klikom na "Dodaj/ažuriraj lotove", ništa se ne dešava

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "SIDEVS"
2. Logovati se kao menadžer.
3. Kliknuti na dugme "Dodaj/ažuriraj lotove"

**Comment by MaidaB** [comment]
Ja sam klonirala ponovo repozitorij i zaista rade ovi buttoni molim te provjeri jesi li povukao ispravnu verziju

**Comment by MaidaB** [comment]
neki problem s lokalnom bazom..
