### ISSUE TITLE
Nema validacije, moze se dodati posve besmislen korisnik

### ISSUE THREAD

**Issue by IrmaKarasoftic** [SoftverInzenjeringETFSA/SI2015Tim1#28]
Komponenta: Administrator - pocetni ekran
commit id: f5e893a
Opis: Validacija postoji samo na e-mailu, mogu se unijeti besmisleni podaci (poput: godina u datumu: 5555)

1.Pokrenuti program
2.Unijeti login podatke (maidab, password)
3. Kliknuti na Dodaj novog korisnika
4.Unijeti sljedece podatke:
![image](https://cloud.githubusercontent.com/assets/11329063/15296655/a2652e76-1b96-11e6-8283-ec419c71f484.png)
5.Korisnik je dodan

![image](https://cloud.githubusercontent.com/assets/11329063/15296528/ffc6440c-1b95-11e6-8055-8c5f9578d6ea.jpg)

**Comment by MaidaB** [comment]
- Po zakonu nije zabranjeno da ime ili prezime sadrže brojeve npr. Elizabeta 3.
- Ogroman broj adresa sadrži brojeve
- Matični broj je ograničen na korištenje brojeva, međutim nismo mogli se ograničiti na JMBG države Bosne i Hercegovine jer postoji mogućnost zapošljavanja radnika koji nisu državljani Bosne i Hercegovine
- Gornja granica za godinu nema smisla jer možda će se aplikacija koristiti i 5555. godine :)
- Polje za radno mjesto sadrži dodatni opis pozicije radnika ili menadžera i može sadržavati brojeve, npr. "Radnik u skladištu br. 2"

**Comment by IrmaKarasoftic** [comment]
Ime i prezime moraju sadrzavati barem 2 slova. Po zakonu nije dozvoljeno da se osoba zove 555 55555, i zivi na adresi 555. (Dakle ime i prezime mogu sadrzavati brojeve, ali ne SAMO brojeve).
Sto se tice gornje granice za godinu, pretpostavljam da ne bi trebalo biti validno da, ako danas zaposlim nekoga imam mogucnost da napisem da sam ga zaposlila sljedeceg mjeseca, ili cak godine, Smisleno je da mogu unijeti neki datum u proslosti, ali ne u buducnosti. (sto implicira da ako se aplikacija bude koristila 5555.godine, radnik ne moze biti unesen sa godinom zaposljavanja 5556.).

**Comment by MaidaB** [comment]
U dokumentaciji nigdje nije navedeno da ce se vrsiti takva vrsta validacije (mala je šansa da će administrator, stručnjak, unositi takve podatke)
Ako je direktor odlučio zaposliti određene ljude nakon što je obavio intervju s njima i potpisao ugovor (u kojem piše da počinju raditi za mjesec dana jer u bivšoj firmi moraju odraditi otkazni rok) može predati administatoru spisak novih zaposlenika a u tom slučaju datum početka rada će biti u budućnosti.

**Comment by hmusovic** [comment]
svaka čast, gasim internete
