### ISSUE TITLE
Nemogucnost izlaza iz aplikacije

### ISSUE THREAD

**Issue by IrmaKarasoftic** [SoftverInzenjeringETFSA/SI2015Tim1#29]
commit id: f5e893a
Opis: Izlaz iz aplikacije je moguc samo na login page-u, sa Administrator - Pocetna stranica nije moguce izaci dok se ne odjavi

Koraci za reproduciranje problema:
1.Login sa podacima maidab, password
2.Klik na X button

Ocekivani rezultat: Izlazak iz aplikacije
Dobijeni rezultat: Nista se nije desilo

**Comment by MaidaB** [comment]
Ovo nije bug, već smo namjerno onemogućili prisilan izlazak iz aplikacije bez da se korisnik zaista odjavi.
