### ISSUE TITLE
Modifikacija korisnika

### ISSUE THREAD

**Issue by IrmaKarasoftic** [SoftverInzenjeringETFSA/SI2015Tim1#30]
Komponenta: Administrator - Modifikacija korisnika
commit id: f5e893a
Opis: Korisnik se ne moze izabrati u comboboxu, mora se poceti kucati ime kako bi postao opcija.

1.Unijeti login podatke: maidab, password
2.Kliknuti na dugme "Dodaj novog korisnika"
3.Unijeti sve potrebne podatke.
4.Kliknuti da dugme "Dodaj"
5.Kliknuti na modifikuj korisnika

U comboboxu za izbor korisnika ne postoji nijedan korisnik. Kada se pocne tipkati ime, izbaci postojeceg korisnika, ali ako se u combobox unese i korisnik koji ne postoji, on postaje opcija comboboxa.
![image](https://cloud.githubusercontent.com/assets/11329063/15297091/ad599ea0-1b98-11e6-88d5-06df722cdbcd.png)

**Comment by MaidaB** [comment]
Ono što je opisano kao problem je upravo ono što i jesmo zamislili. Dopustili smo da se u combo box unese i nešto opcionalno ali učitavanje će prijaviti grešku. Nije cilj comboboxa da prikaže postojeće korisnike (jer ih može biti na hiljade pa bi to bilo veoma nepregledno) već služi kao autocomplete radi bržeg unosa korisnika.
