### ISSUE TITLE
Nemogucnost dodavanja skladista

### ISSUE THREAD

**Issue by IrmaKarasoftic** [SoftverInzenjeringETFSA/SI2015Tim1#31]
Komponenta: Dodaj/azuriraj lot u skladiste, Evidencija lotova
commit ID: 5dff93c

Opis problema: Na vise formi sam pokusala pronaci gdje se skladiste dodaje, nisam uspjela. Ni u jednom comboboxu ne postoji skladiste, a s time nije moguce ni dodati lijek, evidentirati lot...

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "SIDEVS"
2. Logovati se kao korisnik koji nije admin
3. Kliknuti na evidencija lotova / Dodaj/azuriraj lijek u skladistu
4. Kliknuti na combobox za prikaz opcija

![image](https://cloud.githubusercontent.com/assets/11329063/15297450/7e534a46-1b9a-11e6-938d-3f587f39fa35.png)

![image](https://cloud.githubusercontent.com/assets/11329063/15297462/8fd45774-1b9a-11e6-8721-d72d1d23b168.png)

**Comment by MaidaB** [comment]
Nije bug, s obzirom da su fiksno 2 skladišta, korisnici ih nigdje ne unose već se već nalaze u bazi.``
