### ISSUE TITLE
Transakcije kupca-mogućnost unosa datuma koji je poslije današnjeg datuma

### ISSUE THREAD

**Issue by NerminBoja** [SoftverInzenjeringETFSA/SI2015Tim1#32]
Komponenta: Transakcije kupca
commit ID: ef41547fdb911b57c8444b96aeeb82fc335f60b0

Opis problema: Kod unosa datuma vremenskog perioda, tj. od kad-do kad, moguce je u polje "do" unijeti datum koji je poslije današnjeg datuma, što mislim da nema logike

![si-test-tim1](https://cloud.githubusercontent.com/assets/11291037/15298040/ad0823ae-1b9d-11e6-8df6-0847eb942283.jpg)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "SIDEVS".
2. Logovati se kao menadžer.
3. Kliknuti na "Transakcije kupca".
4. Unijeti datum koji je poslije današnjeg u polje "Do"

**Comment by MaidaB** [comment]
Potpuno bespotrebno gubljenje vremena developera na validaciju bez koje će izvještaj biti apsolutno ispravan. U slučaju postavljanja gornje granice datuma Do onda bi bilo logično postaviti i donju granicu za datum OD što nema smisla niti potrebe.
