### ISSUE TITLE
Nemogucnost brisanja korisnika

### ISSUE THREAD

**Issue by hmusovic** [SoftverInzenjeringETFSA/SI2015Tim1#33]
Komponenta: Administrator - Brisanje korisnika
commit id: f5e893a
Opis: Korisnik se ne moze izabrati u comboboxu kojeg korisnika želi izbrisati.

1.Unijeti login podatke: MAIDAB, password
2.Kliknuti na dugme "Dodaj novog korisnika"
3.Unijeti sve potrebne podatke.
4.Kliknuti da dugme "Dodaj"
5.Kliknuti na obrisi korisnika

U comboboxu za izbor korisnika ne postoji nijedan korisnik. 
http://pokit.org/get/?11bef9bfd107f9f14cbc9ef9d8241b0f.jpg

**Comment by MaidaB** [comment]
Nije bug u pitanju. Morate unijeti korisnika, a combobox samo pomaže za autocomplete podataka koji se nalaze u bazi nakon što otkucate slovo ili više njih.
