### ISSUE TITLE
Mogućnost dodavanja kupca sa besmislenim podacima

### ISSUE THREAD

**Issue by rhoso1** [SoftverInzenjeringETFSA/SI2015Tim1#37]
Komponenta: Menadžer-Početni ekran - dodaj kupca
commit id: 8ab5773
Opis: Prilikom dodavanja novog kupca na početnom ekranu menadžera moguće je unijeti besmislene podatke, pri čemu se uspješno doda taj kupac.
Koraci za reproduciranje problema:
1.Pokrenuti program
2. Unijeti podatke kako bi se logovali kao menadžer
3. Odabrati opciju za dodavanje novog kupca.
4.Unijeti podatke kao na slici
![image](https://cloud.githubusercontent.com/assets/11329023/15304129/e742ba70-1bbb-11e6-9b7b-6b6899f3146f.png)
5. Kliknuti na dugme dodaj
6. Kupac se uspješno dodaje
![image](https://cloud.githubusercontent.com/assets/11329023/15304141/f622e7cc-1bbb-11e6-86a0-64ca252ce5f6.png)

**Comment by MaidaB** [comment]
Za validaciju "besmislenih" imena i prezimena bila bi nam potrebna lista svih mogućih imena, prezimena i adresa na svijetu kao i onih koje će nakad neko u nekom momentu izmisliti (vaoma je popularno da roditelji izmišljaju imena koja niko na svijetu nema). Uglavnom, validacija imena, prezimena i adresa je apsolutno nemoguća.
