### ISSUE TITLE
Funkcionalni zahtjev iz SRSa "Pretraga lijekova na stanju" neispravno realizovan 

### ISSUE THREAD

**Issue by IrmaKarasoftic** [SoftverInzenjeringETFSA/SI2015Tim1#39]
Komponenta: Pretraga lijeka

commit ID: 5dff93c

Opis problema: U SRS-u se nalazi informacija da izvjestaj sadrzi informacije o kolicini, broju lota i cijeni za uneseni lijek. Izvjestaj ne prikazuje sve navedene podatke

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "SIDEVS"
2. Logovati se kao radnik
3. Kliknuti na evidencija lotova

![image](https://cloud.githubusercontent.com/assets/11329063/15305074/31b800b0-1bc1-11e6-8c83-527375a70999.png)

Ocekivani podaci o kolicini, broju lota i cijeni za uneseni lijek
Dobijeni podaci o skladistu i kolicini lijeka:
![image](https://cloud.githubusercontent.com/assets/11329063/15305172/c542b64a-1bc1-11e6-9c65-c408bfec2e71.png)

**Comment by MaidaB** [comment]
Nećemo mijenjati jer u opisu piše da korisnik provjerava da li se lijek nalazi u skladištu i u kolikoj količini (smisao pretrage). Greška je u SRSu (procesiranje i izlaz)
