### ISSUE TITLE
Detaljan prikaz funkcionalnih zahtjeva - numeracija stranica

### ISSUE THREAD

**Issue by IrmaKarasoftic** [SoftverInzenjeringETFSA/SI2015Tim1#41]
U fajlu: https://github.com/SoftverInzenjeringETFSA/SI2015Tim1/blob/master/Task3/Detaljan%20prikaz%20zahtjeva%20-%20svi%20dijagrami.pdf
nisu numerisane stranice
![image](https://cloud.githubusercontent.com/assets/11329063/15305822/d84c22b8-1bc5-11e6-8aa7-003e5a807d24.png)

**Comment by MaidaB** [comment]
Ne spada ni u jednu kategoriju valdinih bugova :

"Pored očiglednih stvari (program se krahira ili ne daje očekivan rezultat), validni bugovi su i sljedeći:
- neusaglašenost SRSa i dizajna
- neusaglašenost SRSa i koda
- neusaglašenost dizajna i koda (class, erd...)
- loš dizajn (sintaksne greške u UMLu)
- neusaglašenost UIS i koda
- validacija unosa (prolaze nevalidni podaci npr. nevalidan datum, JMBG...) "
