### ISSUE TITLE
Nevalidan datum početka rada 

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#44]
Komponenta:
Dodavanje Korisnika

commit ID:
806fd1c

Opis problema:
Pri dodavanju korisnika, moguće je staviti datum zaposlenja u budućnosti bez prijave greške.
1.Nakon prijave na sistem, otvoriti interfejs za dodavanje novog korisnika
2.U polje datuma početka rada, ukucati npr. 25.12.2020.

Dobijeni rezultat:
Korisnik uspjesno upisan u bazu.

Ocekivani rezultat:
Prijava greske, usljed neispravnog datuma.

**Comment by MaidaB** [comment]
Administrator može dobiti spisak radnika koje mora unijeti nakon što su primljeni na intrevjuju u petak, a oni počinju raditi od ponedjeljka (što je onda datum u budućnosti)

**Comment by Hadziarapovic** [comment]
Govorim o 10-20 godina u naprijed.

**Comment by MaidaB** [comment]
Niti je naručilac tražio takvu validaciju, niti je ona navedena u dokumentaciji, stoga nema apsolutno nikakve potrebe za njom.
