### ISSUE TITLE
Neinformisanje korisnika o dešavanjima pri dodavanju korisnika.

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#45]
Komponenta:
 Dodavanje Korisnika

commit ID:
 806fd1c 

Opis problema:
 Neiformisanje korisnika o greškama pri unosu vrijednosti na poljima za dodavanje novog korisnika.
 Unos izvršen na sljedeći način : 
![bla](https://cloud.githubusercontent.com/assets/11289714/15344971/5cb6c4aa-1cab-11e6-87e5-1cfa2dfd9f1c.png)

 1.Nakon prijave na sistem, otvoriti interfejs za dodavanje novog korisnika
 2.Popuniti polja.
 3.Klikom na dugme dodaj, ništa se ne dešava. Korisnik nije upisan u bazu niti je korisnik obavješten o  potencijalnim greškama u unosu.

 Dobijeni rezultat:
 Ništa.

 Ocekivani rezultat:
 Prijava greške ili upis u bazu (uz nevalidna polja imena i prezimena u navedenom primjeru).

**Comment by MaidaB** [comment]
Vjerovatno niste dobro pritisnuli dugme

**Comment by Hadziarapovic** [comment]
Pritisnula sam dugme, ali je stvar da ne mozete ni dodati vise od 1 korisnika u bazu tako da je ovo bug!
