### ISSUE TITLE
Nemoguća modifikacija korisnika

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#46]
Komponenta:
 Modifikacija Korisnika

commit ID:
  30041a0 

Opis problema:
Nakon dodavanja jednog korisnika u bazu, očekivana je funkcionalnost modifikacije istog. Nakon otvaranja interfejsa za modifikaciju, postojeći korisnici se ne prikazuju u combo box-u, samim tim ni funkcionalnost nije implementirana.
 1.Nakon prijave na sistem, otvoriti interfejs za modifikaciju korisnika.

Dobijeni rezultat:
 Prazan combo box iako postoje korisnici u bazi.

Očekivani rezultat:
 Prikaz postojećih korisnika u combo box-u (neophodno za dalju modifikaciju)

**Comment by MaidaB** [comment]
Nije u pitanju combobox koji prikazuje sve podatke iz baze s obzirom da ih moze biti na stotitne. Morate unijeti korisnika, a combobox samo pomaže za autocomplete podataka koji se nalaze u bazi nakon što otkucate slovo ili više njih.

**Comment by Hadziarapovic** [comment]
Ovako ste naveli i u SRS-u. Ovo je ipak bug. 
![img](https://cloud.githubusercontent.com/assets/11289714/15356389/a86bf9cc-1cf8-11e6-898e-1bf4e2c9d466.png)
