### ISSUE TITLE
Dodavanje korisnika više puta

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#47]
##![visekorisnika](https://cloud.githubusercontent.com/assets/11289714/15344953/372685b8-1cab-11e6-9eb6-8d060372c013.png)
Komponenta:
Dodaj kupca

commit ID:
 30041a0  

Opis problema:
 Nakon prijave na sistem sa nalogom radnika, biramo dodavanje kupaca. Kupca sa istim podacima je moguće dodati više puta bez prijave greške.
 1.Prijava na sistem sa nalogom radnika.
1. Klik na dugme Dodaj.
2. Dva (ili više) puta unos istih podataka.
3. Korisnik spašen u bazu svaki put. 

Dobijeni rezultat:
 Upis istih kupaca u bazu.

Očekivani rezultat:
 Poruka da kupac sa tim podacima već postoji.

**Comment by MaidaB** [comment]
Mogu postojati ljudi sa istim imenom i prezimenom. Ono po cemu ih jedinstveno identificiramo u aplikaciji je email.

**Comment by Hadziarapovic** [comment]
U naslovu sam pogriješila, ali u ostatku teksta ne. Mislim na kupca kojem se unosi samo ime prezime i adresa. Nema uopste unosa email-a tako da je ovo bug.

**Comment by amarbasic** [comment]
Mora biti spašen u bazu kad ti se gore nazivi razlikuju. Sa razmakom i bez razmaka!

**Comment by Hadziarapovic** [comment]
Svejedno, ne radi dodavanje dvije osobe sa istim Imenom i prezimenom a različitim adresama. Često postoji više osoba koje se isto zovu i prezivaju a razlikuju se po adresi.
![image](https://cloud.githubusercontent.com/assets/11289714/15393801/7f71e96e-1dcf-11e6-9dbb-a8858597d075.png)

**Comment by amarbasic** [comment]
Nasa je greška sto ovdje pise Ime i prezime treba pisati Naziv jer mi radimo sa veleporodajom lijekova a tu su kupci firme. A ne postoje dvije firme s istim nazivom.

**Comment by Hadziarapovic** [comment]
Da, ali ja to ne mogu znati. Prijavljujem samo ono što vidim.
