### ISSUE TITLE
Brisanje kupca

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#48]
Komponenta:
Obriši / Brisanje kupca

commit ID:
 30041a0  

Opis problema:
 Nakon prijave na sistem sa nalogom radnika i dodavanja kupaca, klikom na dugme Obriši otvara se   forma sa combo box-om. Međutim postojeći kupci nisu prikazani u istom. 
 1.Prijava na sistem sa nalogom radnika.
 2.Klik na dugme Obriši.
 3.Postojeći kupci se ne prikazuju u combo box-u na formi.

Dobijeni rezultat:
Ništa.

Očekivani rezultat:
Prikaz postojećih kupaca u combo box-u.
![dokaz](https://cloud.githubusercontent.com/assets/11289714/15344926/10b2412e-1cab-11e6-95ae-6e6aa401bbdc.png)

**Comment by MaidaB** [comment]
Nije u pitanju combobox koji prikazuje sve podatke iz baze s obzirom da ih moze biti na stotitne. Morate unijeti korisnika, a combobox samo pomaže za autocomplete podataka koji se nalaze u bazi nakon što otkucate slovo ili više njih.

**Comment by Hadziarapovic** [comment]
Ovako ste naveli u korisničkoj specifikaciji. U svakom slučaju imate neslaganje sa dokumentacijom i ovdje.
![brisanje](https://cloud.githubusercontent.com/assets/11289714/15356477/3c0ab704-1cf9-11e6-921c-2f168636ee81.png)
