### ISSUE TITLE
Ne otvara se interfejs za evidenciju lotova

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#49]
Komponenta:
 Glavni interfejs

commit ID:
 30041a0  

Opis problema:
 Nakon prijave na sistem sa nalogom radnika, klikom na dugme Evidencija lota se ništa ne dešava.
 1.Prijava na sistem sa nalogom radnika.
 2.Klik na dugme Evidencija lotova.

(Isto se dešava i pri prijavi sa nalogom menadžera)

Dobijeni rezultat:
 Ništa.

Očekivani rezultat:
Prikaz forme za evidenciju lotova.

![zaradnika](https://cloud.githubusercontent.com/assets/11289714/15345137/ce7869c6-1cac-11e6-90db-530bcc21b6e7.png)

**Comment by MaidaB** [comment]
Kod nas radi kao i kod drugih testera provjerite da li je problem u vasem Eclipsu ili da niste kreirali bazu ispravno

**Comment by Hadziarapovic** [comment]
Provjerila sam sa drugim testerima na koji način kreiraju bazu, oni su mi proslijedili podatke. Baza je kreirana,a greška sljedeća: 2016-05-18 13:19:24 ERROR PocetniEkran:328 - org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by MaidaB** [comment]
Očito je problem kod vas lokalno. Možete na Githubu pogledati kod za view Radnik -> Početni ekran (zadnji put promijenjen 15.5.) i vidjet ćete da je u kodu sve uredu i da nema razloga da se nova forma ne otvori.

**Comment by amarbasic** [comment]
Probaj obrisati schemu pa ponovo kreirati. Problem je sto nemas tabele Skladiste kako si navela u prethodnom kao bug...

**Comment by Hadziarapovic** [comment]
To sam i uradila. Evo ponovo vam sve dokumentujem. Ispod je vrijeme kreiranja vaše baze, a nakon toga je prikazan ponovo isti rezultat bez skladišta.
![image](https://cloud.githubusercontent.com/assets/11289714/15402361/1b0f68aa-1df4-11e6-86eb-88627081e105.png)
![image](https://cloud.githubusercontent.com/assets/11289714/15402462/9b3ac51a-1df4-11e6-968c-f4d76ff68f69.png)
