### ISSUE TITLE
Nema lijeka.

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#50]
Komponenta:
Prikaz lijekova

commit ID:
 30041a0  

Opis problema:
 Nakon prijave na sistem sa nalogom menadžera i dodavanja lijeka, klikom na dugme Prikaži lijekova, otvara se nova forma sa combo box-om. Međutim postojeći lijekovi nisu prikazani u istom. Dokumentovano slikom ispod. 
![nemalijeka](https://cloud.githubusercontent.com/assets/11289714/15345239/b2004aa6-1cad-11e6-9355-c6f6ea3cd68a.png)

 1.Prijava na sistem sa nalogom menadžera.
 2.Klik na dugme Evidencija lijekova i dodavanje lijeka.
 3.Lijek se spašava u bazu ali se ne prikazuje u combo box-u na formi.

Dobijeni rezultat:
 Ništa.

Očekivani rezultat:
 Prikaz postojećeg lijeka u combo box-u.

**Comment by MaidaB** [comment]
Nije u pitanju combobox koji prikazuje sve lijekove jer njih u bazi moze biti na hiljade, lijekovi se pocnu prikazivati nakon što počnete kucati slova.

**Comment by Hadziarapovic** [comment]
U svakom slučaju imate neussaglašenost dizajna sa dokumentacijom. (Prema postavci zadatka to je validan bug.)
![lijek](https://cloud.githubusercontent.com/assets/11289714/15356579/d86e7518-1cf9-11e6-9ef2-a1721e5ad0e4.png)
