### ISSUE TITLE
Interfejs se ne poklapa sa dokumentacijom.

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#51]
Komponenta:
Evidencija lijekova

commit ID:
 30041a0  

Opis problema:
 Nakon prijave na sistem sa nalogom menadžera i klika na dugme Evidencija lijekova ustanovit ćemo nedostatak polja za ID -u odnosu na dokumentaciju korisničog interfejsa. Prikazano na slici:
![neslazese](https://cloud.githubusercontent.com/assets/11289714/15345414/f507d714-1cae-11e6-8080-ed2fd95b5dff.png)

 1.Prijava na sistem sa nalogom menadžera.
 2.Klik na dugme Evidencija lijekova.

Dobijeni rezultat:
Nedostaje polje za ID.

Očekivani rezultat:
GUI kao u dokumentaciji.

**Comment by MaidaB** [comment]
ID se generiše automatski i nema potrebe da ga unosi korisnik.

**Comment by Hadziarapovic** [comment]
Labela nije na mjestu. Pogledaj postavku zadatka. 
![zadatak](https://cloud.githubusercontent.com/assets/11289714/15356280/2aec9696-1cf8-11e6-88cd-f8160de52535.png)

**Comment by MaidaB** [comment]
Stavljene su labele documentation i wontfix, samo je obrazlozeno zbog cega necemo nista mijenjati.

**Comment by Hadziarapovic** [comment]
Ne morate vi mijenjati, ali label treba biti BUG!

**Comment by MaidaB** [comment]
Prije početka rada na nekom fakultetskom zadatku, preporučujem da se pročitaju upustva asistenta kako se taj zadatak ispravno obavlja. Pravila za ovaj projektni zadatak mogu se pronaći na slijedećem linku:

http://c2.etf.unsa.ba/mod/resource/view.php?inpopup=true&id=46109
