### ISSUE TITLE
Baza podataka - neispravno

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#53]
Komponenta:
Baza podataka

commit ID:
 30041a0  

Opis problema:

![baza](https://cloud.githubusercontent.com/assets/11289714/15357376/b048356a-1cfe-11e6-92ec-8141050fa1ee.png)
Generiše se baza, međutim nedostaje tabela skladište nakon tog procesa.
![baza](https://cloud.githubusercontent.com/assets/11289714/15357458/4dd2325e-1cff-11e6-8842-99e00bfd8704.png)

Dobijeni rezultat:
Fali tabela u bazi.

Očekivani rezultat:
Generisana baza sa svim neophodnim tabelama.

**Comment by amarbasic** [comment]
Ne znam zašto ali evo ja sam sad obrisao bazu i pokrenuo aplikaciju

![image](https://cloud.githubusercontent.com/assets/11327911/15387352/f8e08f4e-1dac-11e6-8f01-23dd794940e0.png)

**Comment by MaidaB** [comment]
http://img.prntscr.com/img?url=http://i.imgur.com/tr5Bw0B.png

Jasno se vidi da se tabela Skladista nalazi u hibernate konfiguraciji i da ona nije mijenjana od 14.05.

**Comment by Hadziarapovic** [comment]
Pokazat ću vam jer druge nema.
