### ISSUE TITLE
Brisanje kupca ne uzrokuje brisanje istog iz baze

### ISSUE THREAD

**Issue by tcerimagic** [SoftverInzenjeringETFSA/SI2015Tim1#54]
Komponenta:
Obriši / Brisanje kupca/ Baza

commit ID:
 019f8f7

Opis problema:
Nakon prijave na sistem sa nalogom radnika i dodavanja kupaca, klikom na dugme Obriši otvara se forma za brisanje. Nakon što unesemo traženog radnika i kliknemo na drugme Izbriši, dobijamo informaciju o uspješnom brisanju, a isti radnih ostaje u bazi.

1.Prijava na sistem sa nalogom radnika.
2.Klik na dugme Obriši.
3.Odabir željenog radnika za brisanje.
4.Klik na dugme Izbriši
5.Obavještenje o uspješnom brisanju
6.Uvid u stanje tabele kupac

Dobijeni rezultat: 
- Obrisani kupac ostao u bazi podataka

Očekivani rezultat:
-Obrisani kupac uklonjen iz baze i oslobođeni memorijski resursi

**Comment by fademovic** [comment]
Radnik može dodavati i brisati samo kupce, administrator je taj koji briše radnike. S toga ne vidim logiku zašto bi kroz GUI za brisanje kupca, brisao radnika. Uostalom i treba da se ne može radnik obrisati kroz GUI za brisanje kupca

![2](https://cloud.githubusercontent.com/assets/16963805/15393253/a5957e60-1dcc-11e6-805a-b32cfd1c87c5.PNG)

**Comment by tcerimagic** [comment]
Pogresno sam se izrazio, isti kupac ostaje u bazi. I nakon toga je ponovo dostupan na ostalim formama kroz combobox, a ne bi trebao biti.
