### ISSUE TITLE
Nemogućnost zatvaranja forme na dugme X ili nedostatak uputa o koracima za zatvaranje

### ISSUE THREAD

**Issue by tcerimagic** [SoftverInzenjeringETFSA/SI2015Tim1#55]
Komponenta:
Početni ekran- Radnik

commit ID:
019f8f7

Opis problema:
Nakon prijave na sistem sa nalogom radnika na početnom ekranu je blokirano dugme X za izlaz iz sistema. To predstavlja Windows opcija koja postoji na UI-u i samim tim treba imati neku funkcionalnost. U slučaju da ste htjeli onemogućiti log out pomoću toga, onda barem treba notifikacija šta da se uradi. 

1.Prijava na sistem sa nalogom radnika.
2.Klik na dugme "X" u gornjem desnom ćošku prozora

Dobijeni rezultat:
- Ništa

Očekivani rezultat:
- Zatvaranje forme ili obavijest o potrebnim koracima za zatvaranje forme

**Comment by fademovic** [comment]
S obzirom da postoji button "Odjava", korisnik intuitivno može  zaključiti kako da izadje iz aplikacije, bez da mu se dodatno objašnjava. Onemogućavanje izlaza iz aplikacije klikom na dugme X je dizajnerska sloboda.

![1](https://cloud.githubusercontent.com/assets/16963805/15393124/d45b3510-1dcb-11e6-8815-47b539a20385.PNG)

**Comment by tcerimagic** [comment]
Mislim da se Dean nece sloziti.  Bug je ako se na dugme za izlaz ne moze izaci. Ono onda ne treba da postoji tu.

**Comment by MaidaB** [comment]
Eclipse to ne dozvoljava

**Comment by MaidaB** [comment]
duplicate #29
