### ISSUE TITLE
Izvještaj o ulazima i izlazima na osnovu lota -> kreira izvjestaj sa netačnim podacima

### ISSUE THREAD

**Issue by NerminBoja** [SoftverInzenjeringETFSA/SI2015Tim1#58]
Komponenta: Menadžer- Izvještaj o ulazima i izlazima na osnovu lota
commit id: ef41547fdb911b57c8444b96aeeb82fc335f60b0
Opis: Prvo unesemo nekoliko lotova klikom na dugme "Evidencija lotova". Nakon toga kliknemo na "Izvještaj o ulazima i izlazima na osnovu lota" i u polje "Odaberi lot" upišemo neki od maloprije unesenih lotova. Kliknemo na dugme "Pretraga" i ispisu nam se podaci za taj lot, ali netačni.

Koraci za reproduciranje problema:
1.Unijeti menadžerske login podatke
2.Kliknuti na dugme "Evidencija lotova"
3.Unijeti sljedece podatke:
![evidencija lota](https://cloud.githubusercontent.com/assets/11291037/15336124/4d07ab54-1c75-11e6-9b30-1cc99967f76d.jpg)

4.Nakon toga izaći iz "Evidencije lotova" i kliknuti na dugme " Izvještaj o ulazima i izlazima na osnovu lota" i unijeti sljedeće:
![lot2](https://cloud.githubusercontent.com/assets/11291037/15336165/78262df6-1c75-11e6-8056-08ca871472d6.jpg)
6.Generiši izvještaj

Rezultat: Kreira se neispravan izvještaj

**Comment by NerminBoja** [comment]
Tek kada se korisnik odjavi, pa ponovo prijavi i klikne dugme "Izvještaj o ulazima i izlazima na osnovu lota" te unese broj lota sa gornje slike, tek se onda prikaže stvarno stanje, onako kako bi trebalo da bude.

**Comment by amarbasic** [comment]
Ok. hvala da dodatnom obavjestenju !
