### ISSUE TITLE
Neusaglašenost ponovo

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#65]
Komponenta:
 Interfejs za radnika

commit ID:
 30041a0  

Opis problema:
 Nakon prijave na sistem sa nalogom radnika, klikom na dugme Evidencija lijeka otvara se interfejs na kojem je potrebno unijeti naziv lijeka i proizvođača. Dok su u SRS-u navedeni drugačiji ulazi.
![image](https://cloud.githubusercontent.com/assets/11289714/15428181/224b263a-1e9a-11e6-8632-1cdc2a93f94b.png)

 1.Prijava na sistem sa nalogom radnika.
 2.Klik na dugme Evidencija lijekova.

Dobijeni rezultat:
 Pogrešna forma.
![image](https://cloud.githubusercontent.com/assets/11289714/15428211/4ca0d948-1e9a-11e6-832a-210cc91a0f0f.png)

Očekivani rezultat:
Ista forma kao u SRS-u.

**Comment by MaidaB** [comment]
Gledali ste 1. verziju SRSa objavljenu prije 2 mjeseca, umjesto 2. verzije objavljene prije mjesec dana u kojoj piše:

http://img.prntscr.com/img?url=http://i.imgur.com/ScUvwbD.png

**Comment by Hadziarapovic** [comment]
Gledala sam verziju koja je imenovana "SRS-Tim1-finalna verzija".
