### ISSUE TITLE
Otpis lijekova 

### ISSUE THREAD

**Issue by Hadziarapovic** [SoftverInzenjeringETFSA/SI2015Tim1#66]
Komponenta:
Otpis lijekova

commit ID:
 30041a0  

Opis problema:
Nakon prijave na sistem sa nalogom menadžera, klikom na dugme Otpis lijekova otvara se interfejs na kojem je potrebno unijeti neophodne podatke. Nedostaje dugme za unos količine otpisanog lijeka.

1.Prijava na sistem sa nalogom menadžera.
 2.Klik na dugme Otpis lijekova.
![image](https://cloud.githubusercontent.com/assets/11289714/15442393/2ee44cf4-1ee1-11e6-8870-00942e350662.png)
![image](https://cloud.githubusercontent.com/assets/11289714/15442403/3cb52358-1ee1-11e6-85b5-ab6cd188489f.png)

Dobijeni rezultat:
Forma bez unosa količine.

Očekivani rezultat:
 Ista forma kao u SRS-u.

**Comment by MaidaB** [comment]
Otpisuje se cijeli lot.
